export const CRYPTO_LIST_REQUEST = 'CRYPTO_LIST_REQUEST'
export const CRYPTO_LIST_SUCCESS = 'CRYPTO_LIST_SUCCESS'
export const CRYPTO_LIST_FAIL = 'CRYPTO_LIST_FAIL'

export const CRYPTO_DETAILS_REQUEST = 'CRYPTO_DETAILS_REQUEST'
export const CRYPTO_DETAILS_SUCCESS = 'CRYPTO_DETAILS_SUCCESS'
export const CRYPTO_DETAILS_FAIL = 'CRYPTO_DETAILS_FAIL' 

export const GET_SINGLE_CRYPTO_REQUEST = 'GET_SINGLE_CRYPTO_REQUEST'
export const GET_SINGLE_CRYPTO_SUCCESS = 'GET_SINGLE_CRYPTO_SUCCESS'
export const GET_SINGLE_CRYPTO_FAIL = 'GET_SINGLE_CRYPTO_FAIL' 