export const CRYPTO_LIST_REQUEST = 'CRYPTO_LIST_REQUEST'
export const CRYPTO_LIST_SUCCESS = 'CRYPTO_LIST_SUCCESS'
export const CRYPTO_LIST_FAIL = 'CRYPTO_LIST_FAIL'

export const CRYPTO_DETAILS_REQUEST = 'CRYPTO_DETAILS_REQUEST'
export const CRYPTO_DETAILS_SUCCESS = 'CRYPTO_DETAILS_SUCCESS'
export const CRYPTO_DETAILS_FAIL = 'CRYPTO_DETAILS_FAIL' 