export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'

export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAIL = 'GET_POST_FAIL'

export const PUT_MESSAGE_REQUEST = 'PUT_MESSAGE_REQUEST'
export const PUT_MESSAGE_SUCCESS = 'PUT_MESSAGE_SUCCESS'
export const PUT_MESSAGE_FAIL = 'PUT_MESSAGE_FAIL'

export const GET_ROOM_MESSAGES_REQUEST = 'GET_ROOM_MESSAGES_REQUEST'
export const GET_ROOM_MESSAGES_SUCCESS = 'GET_ROOM_MESSAGES_SUCCESS'
export const GET_ROOM_MESSAGES_FAIL = 'GET_ROOM_MESSAGES_FAIL'
