export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST'
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS'
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL'

export const NEWS_DETAILS_REQUEST = 'NEWS_DETAILS_REQUEST'
export const NEWS_DETAILS_SUCCESS = 'NEWS_DETAILS_SUCCESS'
export const NEWS_DETAILS_FAIL = 'NEWS_DETAILS_FAIL' 

export const BANK_LIST_REQUEST = 'BANK_LIST_REQUEST'
export const BANK_LIST_SUCCESS = 'BANK_LIST_SUCCESS'
export const BANK_LIST_FAIL = 'BANK_LIST_FAIL'

export const BANK_DETAILS_REQUEST = 'BANK_DETAILS_REQUEST'
export const BANK_DETAILS_SUCCESS = 'BANK_DETAILS_SUCCESS'
export const BANK_DETAILS_FAIL = 'BANK_DETAILS_FAIL' 

export const ECONOMY_LIST_REQUEST = 'ECONOMY_LIST_REQUEST'
export const ECONOMY_LIST_SUCCESS = 'ECONOMY_LIST_SUCCESS'
export const ECONOMY_LIST_FAIL = 'ECONOMY_LIST_FAIL'

export const ECONOMY_DETAILS_REQUEST = 'ECONOMY_DETAILS_REQUEST'
export const ECONOMY_DETAILS_SUCCESS = 'ECONOMY_DETAILS_SUCCESS'
export const ECONOMY_DETAILS_FAIL = 'ECONOMY_DETAILS_FAIL' 